openapi: 3.0.2
info:
  title: "銃操作API"
  version: "1.0"
  description: |-
    ## 銃の管理を行うWebAPI定義
    - 銃の管理
    - 銃の画像管理
    - 銃のカテゴリー管理
    - 弾丸の管理
tags:
  - name: "guns"
  - name: "images"
  - name: "categories"
  - name: "bullets"
servers:
  - url: http://localhost:5000/arsenals/api/v1
    description: 開発サーバー
  - url: https://nukomabo.work/arsenals/api/v1
    description: 本番サーバー
paths:
  /guns:
    get:
      summary: 銃取得
      description: |-
        銃取得
      tags:
        - "guns"
      operationId: "fetchGuns"
      parameters:
        - $ref: "./guns/model.yaml#/components/parameters/gunCategory"
      responses:
        200:
          $ref: "./guns/fetch-guns.yaml#/components/responses/OK"
        204:
          description: "NoContent"
        500:
          description: "Internal Server Error"
    post:
      summary: 銃登録
      description: |-
        銃登録
      tags:
        - "guns"
      operationId: "registryGun"
      requestBody:
        $ref: "./guns/registry-gun.yaml#/components/requestBodies/gun"
      responses:
        201:
          $ref: "./guns/registry-gun.yaml#/components/responses/Create"
        400:
          description: |-
            - 銃の名前が被っている
        404:
          description: |-
            - 指定した弾丸IDが存在しない
            - 銃カテゴリーが存在しない
        409:
          description: 銃IDが被った
        500:
          description: "Internal Server Error"

  /guns/{gunId}:
    get:
      summary: 銃取得
      description: |-
        銃取得
      tags:
        - guns
      operationId: "fetchGun"
      parameters:
        - $ref: "./guns/model.yaml#/components/parameters/gunId"
      responses:
        200:
          $ref: "./guns/fetch-gun.yaml#/components/responses/OK"
        400:
          description: |-
            - 銃IDの形式が不正
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"
    delete:
      summary: 銃削除
      description: |-
        銃削除
      tags:
        - guns
      operationId: "deleteGun"
      parameters:
        - $ref: "./guns/model.yaml#/components/parameters/gunId"
      responses:
        204:
          description: "NoContent"
        400:
          description: |-
            - 銃IDの形式が不正
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"
    patch:
      summary: 銃更新
      description: |-
        銃更新
      tags:
        - guns
      operationId: "updateGun"
      parameters:
        - $ref: "./guns/model.yaml#/components/parameters/gunId"
        - $ref: "./guns/model.yaml#/components/parameters/gunFieldMask"
      requestBody:
        $ref: "./guns/update-gun.yaml#/components/requestBodies/update"
      responses:
        200:
          description: "OK"
        400:
          description: |-
            - 銃IDの形式が不正
            - フィールドマスクがない
            - フィールドマスクの値が不正
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"

  /guns/{gunId}/images:
    post:
      summary: 銃画像登録
      description: |-
        銃画像登録
      tags:
        - images
      operationId: "registryGunImage"
      parameters:
        - $ref: "./guns/model.yaml#/components/parameters/gunId"
      requestBody:
        $ref: "./guns/upload-gun-image.yaml#/components/requestBodies/upload"
      responses:
        201:
          $ref: "./guns/upload-gun-image.yaml#/components/responses/Create"
        400:
          description: |-
            - 銃IDの形式が不正
            - 画像データが不正
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"

  /categories:
    get:
      summary: "銃カテゴリー取得"
      description: |-
        銃カテゴリー取得
      tags:
        - "categories"
      operationId: "fetchGunCategories"
      responses:
        200:
          $ref: "./guns/fetch-category.yaml#/components/responses/OK"
        204:
          description: "NoContent"
        500:
          description: "Internal Server Error"
    post:
      summary: "銃カテゴリー登録"
      description: |-
        銃カテゴリー登録
      tags:
        - "categories"
      operationId: "registryGunCategory"
      requestBody:
        $ref: "./guns/registry-category.yaml#/components/requestBodies/registry"
      responses:
        201:
          $ref: "./guns/registry-category.yaml#/components/responses/Create"
        400:
          description: |-
            Bad Request
            - カテゴリー名が被っている
        500:
          description: "Internal Server Error"

  /categories/{categoryId}:
    delete:
      summary: 銃カテゴリー削除
      description: |-
        銃カテゴリー削除
      tags:
        - "categories"
      operationId: "deleteGunCategory"
      parameters:
        - $ref: "./guns/model.yaml#/components/parameters/categoryId"
      responses:
        204:
          description: "NoContent"
        400:
          description: |-
            - カテゴリーIDの形式が不正
            - 1件でもカテゴリーが銃に紐づいている場合、削除不可
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"
    patch:
      summary: 銃カテゴリー更新
      description: |-
        銃カテゴリー更新
      tags:
        - "categories"
      operationId: "updateGunCategory"
      parameters:
        - $ref: "./guns/model.yaml#/components/parameters/categoryId"
        - $ref: "./guns/model.yaml#/components/parameters/categoryFieldMask"
      requestBody:
        $ref: "./guns/update-category.yaml#/components/requestBodies/update"
      responses:
        200:
          description: OK
        400:
          description: |-
            - 銃カテゴリーIDの形式が不正
            - フィールドマスクがない
            - フィールドマスクの値が不正
            - 銃カテゴリー名称が被っている
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"

  /bullets:
    get:
      summary: 弾丸取得
      description: |-
        弾丸取得
      tags:
        - bullets
      operationId: "fetchBullets"
      responses:
        200:
          $ref: "./bullets/fetch-bullets.yaml#/components/responses/OK"
        204:
          description: "NoContent"
        500:
          description: "Internal Server Error"
    post:
      summary: 弾丸登録
      description: |-
        弾丸登録
      tags:
        - bullets
      operationId: "registryBullet"
      requestBody:
        $ref: "./bullets/registry-bullet.yaml#/components/requestBodies/request"
      responses:
        201:
          $ref: "./bullets/registry-bullet.yaml#/components/responses/Create"
        400:
          description: |-
            - 弾丸名が被っている
        500:
          description: "Internal Server Error"

  /bullets/{bulletId}:
    get:
      summary: 弾丸取得
      description: |-
        弾丸取得
      tags:
        - bullets
      operationId: "fetchBullet"
      parameters:
        - $ref: "./bullets/model.yaml#/components/parameters/bulletId"
      responses:
        200:
          $ref: "./bullets/fetch-bullet.yaml#/components/responses/OK"
        400:
          description: |-
            BadRequest
            - 弾丸IDが不正
        404:
          description: |-
            Not Found
            - 弾丸が存在しない
        500:
          description: "Internal Server Error"
    delete:
      summary: 弾丸削除
      description: |-
        弾丸削除
        - 銃に弾丸が1件でも紐づいている場合は削除不可
      tags:
        - bullets
      operationId: "deleteBullet"
      parameters:
        - $ref: "./bullets/model.yaml#/components/parameters/bulletId"
      responses:
        204:
          description: "NoContent"
        400:
          description: |-
            - 弾丸IDの形式が不正
            - 弾丸を削除することによって銃に紐づいている弾丸が0件になる場合は削除不可
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"
    patch:
      summary: 弾丸更新
      description: |-
        弾丸更新
      tags:
        - bullets
      operationId: "updateBullet"
      parameters:
        - $ref: "./bullets/model.yaml#/components/parameters/bulletId"
        - $ref: "./bullets/model.yaml#/components/parameters/fieldMask"
      requestBody:
        $ref: "./bullets/update-bullet.yaml#/components/requestBodies/update"
      responses:
        200:
          description: OK
        400:
          description: |-
            - 弾丸IDの形式が不正
            - フィールドマスクがない
            - 許可されているフィールドマスクの値でない
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"
