openapi: 3.0.2
info:
  title: "common"
  version: "1.0"
paths: {}
components:
  schemas:
    BaseResponse:
      title: レスポンス
      type: object
      properties:
        error:
          $ref: "#/components/schemas/Error"

    Error:
      title: エラー
      type: object
      properties:
        message:
          title: メッセージ
          type: string
          example: null
      required:
        - message
