openapi: 3.0.2
info:
  title: "弾丸API"
  version: "1.0"
tags:
  - name: bullets
paths:
  /api/bullets:
    get:
      summary: 弾丸取得
      description: |-
        弾丸取得
      tags:
        - bullets
      responses:
        200:
          $ref: "./fetch-bullets.response.yaml#/components/responses/OK"
        204:
          description: "NoContent"
        500:
          description: "Internal Server Error"
    post:
      summary: 弾丸登録
      description: |-
        弾丸登録
      tags:
        - bullets
      requestBody:
        $ref: "./registry-bullet.request.yaml#/components/requestBodies/request"
      responses:
        201:
          $ref: "./registry-bullet.response.yaml#/components/responses/Create"
        400:
          description: |-
            Bad Request
            - 弾丸名が被っている
        500:
          description: "Internal Server Error"

  /api/bullets/{bulletId}:
    get:
      summary: 弾丸取得
      description: |-
        弾丸取得
      tags:
        - bullets
      parameters:
        - $ref: "./model.yaml#/components/parameters/bulletId"
      responses:
        200:
          $ref: "./fetch-bullet.response.yaml#/components/responses/OK"
        400:
          description: |-
            BadRequest
            - 弾丸IDが不正
        404:
          description: |-
            Not Found
            - 弾丸が存在しない
        500:
          description: "Internal Server Error"
    delete:
      summary: 弾丸削除
      description: |-
        弾丸削除
        - 弾丸を削除することによって銃に紐づいている弾丸が0件になる場合は削除不可
      tags:
        - bullets
      parameters:
        - $ref: "./model.yaml#/components/parameters/bulletId"
      responses:
        204:
          description: "NoContent"
        400:
          description: |-
            Bad Request
            - 弾丸IDの形式が不正
            - 弾丸を削除することによって銃に紐づいている弾丸が0件になる場合は削除不可
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"
    patch:
      summary: 弾丸更新
      description: |-
        弾丸更新
      tags:
        - bullets
      parameters:
        - $ref: "./model.yaml#/components/parameters/bulletId"
        - $ref: "#/components/parameters/fieldMask"
      requestBody:
        $ref: "./update-bullet.request.yaml#/components/requestBodies/update"
      responses:
        200:
          description: OK
        400:
          description: |-
            Bad Request
            - 弾丸IDの形式が不正
            - フィールドマスクがない
            - 許可されているフィールドマスクの値でない
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"

components:
  parameters:
    fieldMask:
      name: "fieldMask"
      in: query
      allowEmptyValue: false
      description: |-
        弾丸更新の項目
      required: true
      schema:
        type: string
        enum:
          - "damage"
          - "name"
