openapi: 3.0.2
info:
  title: "弾丸更新リクエスト"
  version: "1.0"
paths: {}
components:
  requestBodies:
    update:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              damage:
                $ref: "./model.yaml#/components/schemas/Damage"
              name:
                $ref: "./model.yaml#/components/schemas/bulletName"
