openapi: 3.0.2
info:
  title: "弾丸更新"
  version: "1.0"
paths: {}
components:
  requestBodies:
    update:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/updateBulletRequest"

  schemas:
    updateBulletRequest:
      title: 弾丸更新リクエスト
      type: object
      properties:
        damage:
          $ref: "./model.yaml#/components/schemas/Damage"
        name:
          $ref: "./model.yaml#/components/schemas/bulletName"
