openapi: 3.0.2
info:
  title: "銃のモデル"
  version: "1.0"
paths: {}
components:
  parameters:
    gunFieldMask:
      in: query
      name: "fieldMask"
      description: |-
        銃の更新項目
      required: true
      schema:
        type: string
        enum:
          - name
          - category
          - capacity
          - bullets
    gunId:
      in: path
      name: "gunId"
      required: true
      schema:
        $ref: "#/components/schemas/gunId"
    gunCategory:
      in: query
      name: "category"
      required: false
      schema:
        $ref: "#/components/schemas/gunCategoryId"

    categoryFieldMask:
      name: "fieldMask"
      in: query
      required: true
      schema:
        type: string
        enum:
          - name
    categoryId:
      in: path
      name: "categoryId"
      required: true
      schema:
        $ref: "#/components/schemas/gunCategoryId"

  schemas:
    gunId:
      title: 銃ID
      type: string
      pattern: '^G-\d{4}$'
      example: "G-0015"

    gunName:
      title: 銃名称
      type: string
      format: string
      minLength: 1
      maxLength: 20
      example: "Glock22"

    gunCapacity:
      title: 装弾数
      type: number
      format: int32
      minimum: 1
      maximum: 5000
      example: 17

    gunImage:
      title: 銃の画像
      type: string
      format: binary

    gunImageUrl:
      title: 銃の画像のURL
      type: string
      format: uri
      example: "https://arsenals/assets/guns/images/G-0001/glock22.png"

    Gun:
      title: 銃
      description: |-
        - id
        - 銃の名称
        - カテゴリー
        - 装弾数
        - 使用する弾丸
      type: object
      properties:
        id:
          $ref: "#/components/schemas/gunId"
        name:
          $ref: "#/components/schemas/gunName"
        category:
          $ref: "#/components/schemas/GunCategory"
        capacity:
          $ref: "#/components/schemas/gunCapacity"
        imageUrl:
          $ref: "#/components/schemas/gunImageUrl"
        bullets:
          type: array
          items:
            $ref: "../bullets/model.yaml#/components/schemas/Bullet"

    gunCategoryId:
      title: 銃カテゴリーID
      type: string
      pattern: '^C-\d{4}$'
      example: "C-0051"

    gunCategoryName:
      title: 銃カテゴリー名
      type: string
      example: "ハンドガン"
      maxLength: 50

    GunCategory:
      title: カテゴリー
      type: object
      properties:
        id:
          $ref: "#/components/schemas/gunCategoryId"
        name:
          $ref: "#/components/schemas/gunCategoryName"
