openapi: 3.0.2
info:
  title: "銃操作API"
  version: "1.0"
tags:
  - name: "guns"
  - name: "images"
  - name: "categories"
paths:
  /api/guns:
    get:
      summary: 銃取得
      description: |-
        銃取得
      tags:
        - "guns"
      parameters:
        - $ref: "#/components/parameters/gunCategory"
      responses:
        200:
          $ref: "./fetch-guns.response.yaml#/components/responses/OK"
        204:
          description: "NoContent"
        500:
          description: "Internal Server Error"
    post:
      summary: 銃登録
      description: |-
        銃登録
      tags:
        - "guns"
      requestBody:
        $ref: "./registry-gun.request.yaml#/components/requestBodies/gun"
      responses:
        201:
          $ref: "./registry-gun.response.yaml#/components/responses/Create"
        400:
          description: |-
            Bad Request
            - 銃の名前が被っている
            - 銃カテゴリーが存在しない
        404:
          description: |-
            Not Found
            - 指定した弾丸IDが存在しない
        500:
          description: "Internal Server Error"

  /api/guns/{gunId}:
    get:
      summary: 銃取得
      description: |-
        銃取得
      tags:
        - guns
      parameters:
        - $ref: "#/components/parameters/gunId"
      responses:
        200:
          $ref: "./fetch-gun.response.yaml#/components/responses/OK"
        400:
          description: |-
            Bad Request
            - 銃IDの形式が不正
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"
    delete:
      summary: 銃削除
      description: |-
        銃削除
      tags:
        - guns
      parameters:
        - $ref: "#/components/parameters/gunId"
      responses:
        204:
          description: "NoContent"
        400:
          description: |-
            Bad Request
            - 銃IDの形式が不正
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"
    patch:
      summary: 銃更新
      description: |-
        銃更新
      tags:
        - guns
      parameters:
        - $ref: "#/components/parameters/gunId"
        - $ref: "#/components/parameters/gunFieldMask"
      requestBody:
        $ref: "./update-gun.request.yaml#/components/requestBodies/update"
      responses:
        200:
          description: "OK"
        400:
          description: |-
            Bad Request
            - 銃IDの形式が不正
            - フィールドマスクがない
            - フィールドマスクの値が不正
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"

  /api/guns/{gunId}/images:
    post:
      summary: 銃画像登録
      description: |-
        銃画像登録
      tags:
        - images
      parameters:
        - $ref: "#/components/parameters/gunId"
      requestBody:
        $ref: "./upload-gun-image.request.yaml#/components/requestBodies/upload"
      responses:
        201:
          $ref: "./upload-gun-image.response.yaml#/components/responses/Create"
        400:
          description: |-
            Bad Request
            - 銃IDの形式が不正
            - 画像データが不正
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"

  /api/categories:
    get:
      summary: "銃カテゴリー取得"
      description: |-
        銃カテゴリー取得
      tags:
        - "categories"
      responses:
        200:
          $ref: "./fetch-category.response.yaml#/components/responses/OK"
        204:
          description: "NoContent"
        500:
          description: "Internal Server Error"
    post:
      summary: "銃カテゴリー登録"
      description: |-
        銃カテゴリー登録
      tags:
        - "categories"
      requestBody:
        $ref: "registry-category.yaml#/components/requestBodies/registry"
      responses:
        201:
          $ref: "registry-category.yaml#/components/responses/Create"
        400:
          description: |-
            Bad Request
            - カテゴリー名が被っている
        500:
          description: "Internal Server Error"

  /api/categories/{categoryId}:
    delete:
      summary: 銃カテゴリー削除
      description: |-
        銃カテゴリー削除
      tags:
        - "categories"
      parameters:
        - $ref: "#/components/parameters/categoryId"
      responses:
        204:
          description: "NoContent"
        400:
          description: |-
            Bad Request
            - カテゴリーIDの形式が不正
            - 1件でもカテゴリーが銃に紐づいている場合、削除不可
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"
    patch:
      summary: 銃カテゴリー更新
      description: |-
        銃カテゴリー更新
      tags:
        - "categories"
      parameters:
        - $ref: "#/components/parameters/categoryId"
        - $ref: "#/components/parameters/categoryFieldMask"
      requestBody:
        $ref: "./update-category.yaml#/components/requestBodies/update"
      responses:
        200:
          description: OK
        400:
          description: |-
            Bad Request
            - 銃カテゴリーIDの形式が不正
            - フィールドマスクがない
            - フィールドマスクの値が不正
            - 銃カテゴリー名称が被っている
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"

components:
  parameters:
    gunFieldMask:
      in: query
      name: "fieldMask"
      description: |-
        銃の更新項目
      required: true
      schema:
        type: string
        enum:
          - name
          - category
          - capacity
          - bullets
    gunId:
      in: path
      name: "gunId"
      required: true
      schema:
        $ref: "./model.yaml#/components/schemas/gunId"
    gunCategory:
      in: query
      name: "category"
      required: false
      schema:
        $ref: "./model.yaml#/components/schemas/gunCategoryId"

    categoryFieldMask:
      name: "fieldMask"
      in: query
      required: true
      schema:
        type: string
        enum:
          - name
    categoryId:
      in: path
      name: "categoryId"
      required: true
      schema:
        $ref: "./model.yaml#/components/schemas/gunCategoryId"
