openapi: 3.0.2
info:
  title: "銃登録レスポンス"
  version: "1.0"
paths: {}
components:
  responses:
    Create:
      description: |-
        Create
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../commons/model.yaml#/components/schemas/BaseResponse"
              - type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        $ref: "./model.yaml#/components/schemas/gunId"
                    required:
                      - id
