openapi: 3.0.2
info:
  title: "銃更新リクエスト"
  version: "1.0"
paths: {}
components:
  requestBodies:
    update:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                $ref: "./model.yaml#/components/schemas/gunName"
              category:
                $ref: "./model.yaml#/components/schemas/gunCategoryId"
              capacity:
                $ref: "./model.yaml#/components/schemas/gunCapacity"
              bullets:
                title: 弾丸ID
                type: array
                items:
                  $ref: "../bullets/model.yaml#/components/schemas/bulletId"
