openapi: 3.0.2
info:
  title: "銃カテゴリー更新"
  version: "1.0"
paths: {}
components:
  requestBodies:
    update:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                $ref: "./model.yaml#/components/schemas/gunCategoryName"
            required:
              - name
